import requests
import os
import json
import tempfile
from datetime import datetime

# Trello API credentials - these should match your existing setup
API_KEY = 'bf371933fcd49ba099774ba087050e38'
TOKEN = 'ATTA3f27a64d09d2ceef38759b7f1941ca024bc84c274224f592b84fe11c701398898D4A4EE9'

class VoiceContextUploader:
    def __init__(self, api_key=None, token=None):
        self.api_key = api_key or API_KEY
        self.token = token or TOKEN
        self.temp_dir = tempfile.mkdtemp(prefix='voice_context_')
        print(f"🎙️ VoiceContextUploader initialized")
        print(f"📁 Temp directory: {self.temp_dir}")

    def create_voice_context_file(self, context_data):
        """Create a voice context file from context data"""
        try:
            # Generate filename with timestamp and context ID
            timestamp = datetime.now().strftime('%Y-%m-%d')
            context_id = context_data.get('id', 'unknown')[-8:]
            filename = f"voice_context_{timestamp}_{context_id}.txt"
            
            # Generate file content
            content = self.format_voice_context_content(context_data)
            
            # Write to temporary file
            file_path = os.path.join(self.temp_dir, filename)
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            print(f"📄 Created voice context file: {filename}")
            print(f"📊 Content size: {len(content)} characters")
            
            return {
                'success': True,
                'filename': filename,
                'file_path': file_path,
                'content_size': len(content)
            }
            
        except Exception as e:
            print(f"❌ Error creating voice context file: {e}")
            return {
                'success': False,
                'error': str(e)
            }

    def format_voice_context_content(self, context_data):
        """Format voice context data into structured content"""
        content = f"""# Voice Context Entry
**ID:** {context_data.get('id', 'unknown')}
**Type:** {context_data.get('type', 'unknown')}
**Timestamp:** {datetime.now().isoformat()}
**Confidence:** {context_data.get('confidence', 0)}%

## Summary
{context_data.get('summary', 'No summary available')}

## Raw Transcript
{context_data.get('transcript', 'No transcript available')}

## Semantic Tags
{chr(10).join(f"- {tag}" for tag in context_data.get('tags', []))}

## Actions Extracted
{chr(10).join(f"- {action}" for action in context_data.get('actions', ['No actions extracted']))}

---
Generated by Enhanced Trello Voice OS
Voice Context Manager v1.0
Processing Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

This attachment contains voice context that can be referenced by AI systems.
Usage: "Read the voice context attachments to understand the background."

🎙️ Voice-to-Attachment Pattern: ACTIVE
📎 Context persists with card permanently
🤖 Natural AI integration ready
"""
        return content

    def attach_file_to_card(self, card_id, file_path, attachment_name=None):
        """Attach a local file to the specified Trello card using file upload"""
        url = f"https://api.trello.com/1/cards/{card_id}/attachments"
        
        if not attachment_name:
            attachment_name = os.path.basename(file_path)
        
        query = {
            'key': self.api_key,
            'token': self.token,
            'name': attachment_name
        }
        
        if not os.path.exists(file_path):
            print(f"❌ Error: File not found at {file_path}")
            return False

        try:
            with open(file_path, 'rb') as file_to_upload:
                files = {
                    'file': (os.path.basename(file_path), file_to_upload)
                }
                response = requests.post(url, params=query, files=files)
                response.raise_for_status()  # Raises an exception for 4XX/5XX errors
            
            print(f"✅ Successfully attached '{os.path.basename(file_path)}' to card ID: {card_id}")
            return {
                'success': True,
                'attachment_id': response.json().get('id'),
                'attachment_name': attachment_name,
                'card_id': card_id
            }
            
        except requests.exceptions.RequestException as e:
            print(f"❌ Error attaching file to card {card_id}: {e}")
            if 'response' in locals() and response is not None:
                print(f"Response status: {response.status_code}")
                print(f"Response content: {response.text}")
            return {
                'success': False,
                'error': str(e)
            }
        except Exception as e:
            print(f"❌ An unexpected error occurred: {e}")
            return {
                'success': False,
                'error': str(e)
            }

    def create_and_attach_voice_context(self, card_id, context_data):
        """Complete workflow: create file and attach to card"""
        print(f"🎯 Processing voice context for card: {card_id}")
        
        # Step 1: Create the voice context file
        file_result = self.create_voice_context_file(context_data)
        if not file_result['success']:
            return file_result
        
        # Step 2: Attach the file to the card
        attach_result = self.attach_file_to_card(
            card_id, 
            file_result['file_path'], 
            file_result['filename']
        )
        
        # Combine results
        return {
            'success': attach_result.get('success', False),
            'filename': file_result['filename'],
            'content_size': file_result['content_size'],
            'attachment_id': attach_result.get('attachment_id'),
            'error': attach_result.get('error') if not attach_result.get('success') else None
        }

    def batch_upload_contexts(self, card_id, contexts_list):
        """Upload multiple voice contexts to a card"""
        results = []
        
        print(f"📊 Batch uploading {len(contexts_list)} voice contexts to card {card_id}")
        
        for i, context_data in enumerate(contexts_list, 1):
            print(f"\n🔄 Processing context {i}/{len(contexts_list)}: {context_data.get('type', 'unknown')}")
            
            result = self.create_and_attach_voice_context(card_id, context_data)
            results.append(result)
            
            if result['success']:
                print(f"  ✅ Uploaded: {result['filename']} ({result['content_size']} chars)")
            else:
                print(f"  ❌ Failed: {result.get('error', 'Unknown error')}")
        
        successful_uploads = sum(1 for r in results if r['success'])
        print(f"\n📈 Batch upload complete: {successful_uploads}/{len(contexts_list)} successful")
        
        return results

    def cleanup_temp_files(self):
        """Clean up temporary files"""
        try:
            import shutil
            shutil.rmtree(self.temp_dir)
            print(f"🧹 Cleaned up temporary directory: {self.temp_dir}")
        except Exception as e:
            print(f"⚠️ Warning: Could not clean up temp directory: {e}")

def test_voice_context_upload():
    """Test the voice context upload system with Big Dump card"""
    
    # Your actual Big Dump card ID
    BIG_DUMP_CARD_ID = '68331d0fd76353aebe3e6c44'
    
    # Test voice context data
    test_contexts = [
        {
            'id': 'voice_context_001_bigdump_business',
            'type': 'planning',
            'confidence': 87,
            'summary': 'Q4 business review covering retail expansion, inventory management, and Credit Corp partnership with Fisayo for Mikano car financing.',
            'transcript': 'Alright, so we\'re looking at the Q4 business review and I need to talk through several key initiatives. First off, the retail expansion is going well but we need to address the inventory management issues that came up last month. The credit corp partnership with Fisayo is showing promise, especially with the Mikano car financing deal we discussed.',
            'tags': ['Q4-review', 'retail-expansion', 'credit-corp', 'Fisayo', 'Mikano', 'financing'],
            'actions': ['Message Fisayo about Credit Corp rates', 'Review inventory management issues', 'Follow up on Mikano financing deal']
        },
        {
            'id': 'voice_context_002_bigdump_technical',
            'type': 'technical',
            'confidence': 92,
            'summary': 'Technical infrastructure planning focusing on Trello MCP integration, Voice OS development, and pattern learning system achieving 91% accuracy.',
            'transcript': 'On the tech side, we need to prioritize the Trello MCP integration project. The voice OS system we\'ve been building is coming together nicely. The pattern learning capabilities are testing at 91% accuracy which is better than expected. We should also consider how this integrates with our existing waffle processing workflow.',
            'tags': ['Trello-MCP', 'Voice-OS', 'pattern-learning', '91%-accuracy', 'waffle-workflow'],
            'actions': ['Prioritize Trello MCP integration', 'Test voice OS system', 'Integrate with waffle workflow']
        }
    ]
    
    print("🚀 TESTING ENHANCED VOICE CONTEXT UPLOAD SYSTEM\n")
    
    # Initialize uploader
    uploader = VoiceContextUploader()
    
    try:
        # Batch upload all contexts
        results = uploader.batch_upload_contexts(BIG_DUMP_CARD_ID, test_contexts)
        
        # Show final results
        print("\n" + "="*60)
        print("🎉 VOICE CONTEXT UPLOAD TEST COMPLETED!")
        print("="*60)
        
        successful_uploads = [r for r in results if r['success']]
        failed_uploads = [r for r in results if not r['success']]
        
        print(f"📊 Results Summary:")
        print(f"  - Card ID: {BIG_DUMP_CARD_ID}")
        print(f"  - Contexts processed: {len(test_contexts)}")
        print(f"  - Successful uploads: {len(successful_uploads)}")
        print(f"  - Failed uploads: {len(failed_uploads)}")
        
        if successful_uploads:
            print(f"\n✅ Successfully uploaded attachments:")
            for result in successful_uploads:
                print(f"  - {result['filename']} ({result['content_size']} chars)")
        
        if failed_uploads:
            print(f"\n❌ Failed uploads:")
            for result in failed_uploads:
                print(f"  - Error: {result.get('error', 'Unknown error')}")
        
        print(f"\n🎯 Your Revolutionary Voice-to-Attachment Pattern:")
        print(f"  ✅ Voice context files created and uploaded properly")
        print(f"  ✅ Content persists with cards permanently")
        print(f"  ✅ Natural AI integration: 'read the attachments'")
        print(f"  ✅ No external databases required")
        print(f"  ✅ Scales with existing Trello workflow")
        
        return len(successful_uploads) == len(test_contexts)
        
    finally:
        # Clean up
        uploader.cleanup_temp_files()

if __name__ == "__main__":
    success = test_voice_context_upload()
    if success:
        print("\n🤖 All voice contexts uploaded successfully!")
    else:
        print("\n⚠️ Some uploads failed - check the logs above") 